In [12]:
import pandas as pd
import openpyxl

In [13]:
path = r"H:\3° Ano\Python\3° Etapa\analise_dados\aula4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [14]:
populacao_bruto = pd.read_excel(path, header=None)

In [15]:
populacao_bruto

,0,1,2,3,4,5,6,7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Censo Demográfico 2022: População e Domicílios...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
3,NaN,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,NaN,RO,11,00023,Ariquemes,90353,90353,96833
...,...,...,...,...,...,...,...,...
5572,NaN,DF,53,00108,Brasília,2570160,2572159,2817381
5573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5574,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5576,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
populacao_total = populacao_bruto.iloc[3:5573,1:].copy()

In [19]:
populacao_total

       1   2      3                      4        5        6        7
3     RO  11  00015  Alta Floresta D'Oeste    24392    24392    21494
4     RO  11  00023              Ariquemes    90353    90353    96833
5     RO  11  00031                 Cabixi     6313     6313     5351
6     RO  11  00049                 Cacoal    78574    78574    86887
7     RO  11  00056             Cerejeiras    17029    17029    15890
...   ..  ..    ...                    ...      ...      ...      ...
5568  GO  52  22005             Vianópolis    12548    12548    14956
5569  GO  52  22054         Vicentinópolis     7371     7373     8768
5570  GO  52  22203               Vila Boa     4735     4735     4215
5571  GO  52  22302          Vila Propício     5145     5145     5815
5572  DF  53  00108               Brasília  2570160  2572159  2817381

[5570 rows x 7 columns]

In [20]:
populacao_total.columns = ['UF', 'cod_uf', 'cod_munic', 'municipio', 'pop_2010_sinopse', 'pop_2010', 'pop_2022']

populacao_total['pop_2010'] = pd.to_numeric(populacao_total['pop_2010'])
populacao_total['pop_2022'] = pd.to_numeric(populacao_total['pop_2022'])

populacao_total.head()

,UF,cod_uf,cod_munic,municipio,pop_2010_sinopse,pop_2010,pop_2022
3,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
4,RO,11,00023,Ariquemes,90353,90353,96833
5,RO,11,00031,Cabixi,6313,6313,5351
6,RO,11,00049,Cacoal,78574,78574,86887
7,RO,11,00056,Cerejeiras,17029,17029,15890

In [24]:
populacao_estado = populacao_total.groupby('UF')[['pop_2010', 'pop_2022']].sum().reset_index()

populacao_estado['crescimento'] = populacao_estado['pop_2022'] - populacao_estado['pop_2010']
populacao_estado = populacao_estado.sort_values(by='crescimento', ascending=False)

print(populacao_estado)

populacao_estado.to_csv('populacao_estado_crescimento.csv', index=False, sep=';', encoding='utf-8-sig')

    UF  pop_2010  pop_2022  crescimento
25  SP  41262199  44411238      3149039
23  SC   6248436   7610361      1361925
8   GO   6001789   7056495      1054706
17  PR  10444526  11444380       999854
10  MG  19597330  20539989       942659
12  MT   3035122   3658649       623527
13  PA   7581051   8120131       539080
2   AM   3483985   3941613       457628
5   CE   8451644   8794957       343313
7   ES   3514952   3833712       318760
11  MS   2449024   2757013       307989
15  PE   8796055   9058931       262876
6   DF   2572159   2817381       245222
14  PB   3766528   3974687       208159
9   MA   6574789   6776699       201910
22  RS  10693929  10882965       189036
21  RR    450479    636707       186228
16  PI   3119097   3271199       152102
24  SE   2067852   2210004       142152
19  RN   3168027   3302729       134702
26  TO   1383445   1511460       128015
4   BA  14017071  14141626       124555
0   AC    733559    830018        96459
18  RJ  15989929  16055174        65245
3   AP    669526    733759        64233
20  RO   1562409   1581196        18787
1   AL   3120887   3127683         6796

In [25]:

populacao_municipio = populacao_total[['UF', 'municipio', 'pop_2010', 'pop_2022']].copy()

populacao_municipio['crescimento'] = populacao_municipio['pop_2022'] - populacao_municipio['pop_2010']
populacao_municipio = populacao_municipio.sort_values(by='crescimento', ascending=False)

print(populacao_municipio.head(15))

populacao_municipio.to_csv('populacao_municipio_crescimento.csv', index=False, sep=';', encoding='utf-8-sig')

      UF       municipio  pop_2010  pop_2022  crescimento
114   AM          Manaus   1802014   2063689       261675
5572  DF        Brasília   2572159   2817381       245222
3832  SP       São Paulo  11253503  11451999       198496
3851  SP        Sorocaba    586816    723682       136866
5420  GO         Goiânia   1301912   1437366       135454
141   RR       Boa Vista    284313    413486       129173
4401  SC   Florianópolis    421240    537211       115971
243   PA     Parauapebas    153908    267836       113928
5125  MS    Campo Grande    786774    898100       111326
1340  PB     João Pessoa    723515    833932       110417
3070  MG      Uberlândia    604013    713224       109211
3169  ES           Serra    417330    520653       103323
4450  SC       Joinville    515288    616317       101029
5222  MT          Cuiabá    553202    650877        97675
3757  SP  Ribeirão Preto    604682    698642        93960